from pathlib import Path
p=Path('src/main.js')
s=p.read_text(encoding='utf-8')
old="html+='<details class=\"bone-group\"><summary>全部材质控制</summary><div id=\"materialControls\"></div></details>';"
new="html+='<details class=\"bone-group\"><summary>全部材质控制</summary><div id=\"materialControls\"></div></details><details class=\"bone-group\"><summary>全部 Mesh 显隐</summary><div id=\"meshControls\"></div></details><details class=\"bone-group\"><summary>SpringBone / 物理控制</summary><div id=\"springControls\"></div></details>';"
if old not in s: raise SystemExit('advanced body marker missing')
s=s.replace(old,new,1)
marker="\n}\nfunction renderExpressionControls(){"
insert=r'''
  const meshBox=$('#meshControls');if(meshBox){const meshes=[];vrm?.scene.traverse(o=>{if(o.isMesh)meshes.push(o);});for(const mesh of meshes){const row=document.createElement('label');row.className='switch-row';row.innerHTML=`<span>${mesh.name||mesh.uuid.slice(0,8)}</span><input type="checkbox" ${mesh.visible?'checked':''}>`;row.querySelector('input').onchange=e=>mesh.visible=e.target.checked;meshBox.appendChild(row);}if(!meshes.length)meshBox.textContent='无 Mesh';}
  const springBox=$('#springControls');if(springBox){const sm=vrm?.springBoneManager,joints=[...(sm?.joints||[])],colliders=[...(sm?.colliders||[])];springBox.innerHTML=`<div class="section-toolbar"><button id="springReset" class="secondary-btn">重置物理状态</button><small>${joints.length} joints · ${colliders.length} colliders</small></div>`;$('#springReset').onclick=()=>sm?.reset?.();for(const joint of joints){const st=joint.settings||{},card=document.createElement('div');card.className='material-card';card.innerHTML=`<b>${joint.bone?.name||'Spring Joint'}</b>${rowSlider('刚度 stiffness',0,5,.01,st.stiffness??1)}${rowSlider('阻力 drag',0,1,.01,st.dragForce??.4)}${rowSlider('重力 gravity',0,3,.01,st.gravityPower??0)}${rowSlider('碰撞半径',0,.2,.001,st.hitRadius??0)}${rowSlider('重力方向 X',-1,1,.01,st.gravityDir?.x??0)}${rowSlider('重力方向 Y',-1,1,.01,st.gravityDir?.y??-1)}${rowSlider('重力方向 Z',-1,1,.01,st.gravityDir?.z??0)}`;const q=[...card.querySelectorAll('input[type=range]')];q.forEach(e=>e.oninput=()=>e.parentElement.querySelector('output').textContent=e.value);q[0].oninput=()=>{st.stiffness=+q[0].value;q[0].parentElement.querySelector('output').textContent=q[0].value;};q[1].oninput=()=>{st.dragForce=+q[1].value;q[1].parentElement.querySelector('output').textContent=q[1].value;};q[2].oninput=()=>{st.gravityPower=+q[2].value;q[2].parentElement.querySelector('output').textContent=q[2].value;};q[3].oninput=()=>{st.hitRadius=+q[3].value;q[3].parentElement.querySelector('output').textContent=q[3].value;};const gv=()=>{st.gravityDir?.set?.(+q[4].value,+q[5].value,+q[6].value);for(let i=4;i<7;i++)q[i].parentElement.querySelector('output').textContent=q[i].value;};q[4].oninput=q[5].oninput=q[6].oninput=gv;springBox.appendChild(card);}for(const [i,col] of colliders.entries()){const shape=col.shape;if(!shape||typeof shape.radius!=='number')continue;const card=document.createElement('div');card.className='material-card';card.innerHTML=`<b>Collider ${i+1}</b>${rowSlider('半径',0,.3,.001,shape.radius)}`;const r=card.querySelector('input');r.oninput=()=>{shape.radius=+r.value;r.parentElement.querySelector('output').textContent=r.value;};springBox.appendChild(card);}if(!sm)springBox.innerHTML='<small>该 VRM 未提供 SpringBone Manager。</small>';}
'''
if marker not in s: raise SystemExit('expression function marker missing')
s=s.replace(marker,insert+marker,1)
s=s.replace("version:'0.92-free-life'","version:'0.93-free-life'",1)
p.write_text(s,encoding='utf-8')
